name = "Rhapsodie"
uuid = "d7b96371-e7cf-4969-a096-f980e5147251"
version = "0.1.0"
authors = ["Laurence <ldenneulin@montesquiou.info>"]

[deps]
AstroFITS = "34e54ef0-c5bf-48ab-9e5d-cca51f35ed77"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
OptimPackNextGen = "080ffe24-4a27-4ab0-ad71-7b624e73ef8d"
RhapsodieDirect = "0ed9b2bd-c76c-4f1a-94cb-965bde98f638"

[compat]
AstroFITS = "1.0.0"
RhapsodieDirect = "0.1.0"
